name: internet_beats
description: A Dart library for creating and managing time in Internet Beats.
version: 0.0.1
#homepage: https://www.example.com
#author: morgan <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
