name: internet_beats
description: A Dart library for creating and managing time in Internet Beats.
version: 0.0.1
homepage: https://burl.nyc/internet_beats/
author: Morgan Sandquist <morgannels@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
